name: booker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Gerenciamento de estado
  provider: ^6.0.5

  # Requisições HTTP
  http: ^1.1.0

  # Imagens com cache
  cached_network_image: ^3.3.0

  # Navegação
  go_router: ^13.0.0  # Opcional (mais poderosa que Navigator padrão)

  url_launcher: ^6.3.1  # Para abrir URLs externas

  # Persistência de dados local
  shared_preferences: ^2.2.3  # Para favoritos/histórico

  debounce_throttle: ^2.0.0  # Para debounce em buscas

  connectivity_plus: ^5.0.0

  # Carregamento de páginas web
  webview_flutter:  ^4.0.7  # Para exibir páginas web dentro do app

  # Design e UI
  flutter_rating_bar: ^4.0.1  # Para avaliação em estrelas
  google_fonts: ^6.1.0  # Fontes personalizadas
  shimmer: ^3.0.0  # Efeito de carregamento

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8  # Para code generation
  json_serializable: ^6.7.1  # Para serialização JSON

flutter:
  uses-material-design: true
